### ISSUE TITLE
Follow-up feature to assign/use the IP address previously used: set IP address as static

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1457]
With #1316 and https://github.com/minishift/minishift-centos-iso/pull/164 + https://github.com/minishift/minishift-centos-iso/pull/168 it is possible to assign an IP address for re-use when the virtual machine starts.

This task will allow the user to force the current address to become `static`, so on restart no new address will be assigned.

### Needed tasks

  * [x] allow to assign address to multiple interfaces  
         `DEVICE=[interface]` using multiple files named `/var/lib/networking?` => https://github.com/minishift/minishift-centos-iso/issues/180
  * [x] allow interface to be configured to fallback to dhcp  
         `dhclient [interface]` => added a `USEDHCP` option
  * [x] #1496 feature detection during provisioning; 'minishift-set-ipaddress'
  * [x] #1503 use a more generic solution for the VMDriver usage

### Needs investigation

  * [ ] #1765 set IP address for VirtualBox over the forwarded SSH port

---

**Note**: You need at least ISO: http://artifacts.ci.centos.org/minishift/minishift-centos-iso/master/39/ or higher 

This ISO will also allow an address to be 'fixed' by creating a file called: `/var/lib/minishift/networking` containing something like:

```ini
DEVICE=eth0
IPADDR=10.0.75.128
NETMASK=24
GATEWAY=10.0.75.1
DNS1=8.8.8.8
DNS2=8.8.4.4
```

However, this is currently only implemented for use with Hyper-V. Something like the following should be considered to make this work for the other hypervisors.

  * [x] Allow `minishift ip --static` to lock the IP address that has been assigned on startup
  * [ ] Allow `minishift ip --dhcp` to unlock the IP address to be assigned by DHCP
  * [ ] Use `minishift start --network-ipaddress ...` to set the secondary address, which on provisioning is available as secondary and on reboot will be used.

### Overview

| Hypervisor  | Device           | Remark           |
| --- | --- | --- |
| HyperV | `eth0` | attached to whatever vswitch you choose |
| KVM | `eth1` | `eth0` is attached to `default` and `eth1` to `docker-machines` (both on DHCP) |
| VirtualBox | `eth1` | `eth0` used for local communication; assigned `10.0.2.15` by DHCP |
| xhyve | `eth0` | |

**Comment by budhrg** [comment]
> Allow minishift ip --static to lock the IP address that has been assigned on startup

So, it means, I will get ip which I had assigned during start, right? What about the console link displayed during the output of `minishift start`?

**Comment by gbraad** [comment]
This is related to a todo: https://github.com/minishift/minishift/pull/1391/files#diff-cddd82fc40ac720e0e865b059a276667R176

if `--network-no-dhcp` is added it would be prevented to assign a new DHCP address...  so it would return the correct value, else, as mentioned on the original task, it will return the DHCP address first. This is likely unexpected.

Minikube solves this with a `m update-context` option, but unfortunately we can not do something similar. I rather abstract `host.Driver.GetIP()` in a `GetDriverIP` call, and we use a `minishiftNetwork.GetMachineIP` call... if static is assigned, return known value, else use `GetDriverIP`.

**Comment by budhrg** [comment]
> This is related to a todo

Ok. :+1: 

>  I rather abstract host.Driver.GetIP() in a GetDriverIP call, and we use a minishiftNetwork.GetMachineIP call... if static is assigned, return known value, else use GetDriverIP

Sounds like a plan. :+1:

**Comment by gbraad** [comment]
`--network-no-dhcp` is not needed with the new ISO. I do think a possible abstraction of the IP address is valuable going forward

**Comment by LalatenduMohanty** [comment]
@gbraad I like the idea. Though I do not like the flag names i.e. `--static` and `--dhcp`. I think just one flag is enough to make the IP persistent across stop/start. So a name of the flag should reflect that. 

We should test the idea for sure.

**Comment by LalatenduMohanty** [comment]
This is similar to the feature request https://github.com/minishift/minishift/issues/41 . Though there is a subtle difference but the objective is almost same.

**Comment by gbraad** [comment]
The flags are to lock and unlock, and are in line with the workaround
scripts that go around. This was the motivation for these options.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
In the current state, #41 is impossible to implement. Unless we use a way
to also attach IP information into the user data.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
Note: You need at least ISO: http://artifacts.ci.centos.org/minishift/minishift-centos-iso/master/39/ or higher

**Comment by gbraad** [comment]
I will focus for the current cycle on VirtualBox, as there is a possibility to also assign an IP address early in the process. This is due to the fact that VirtualBox sets up a portforwarding for SSH to localhost. Even if the node has a host-only address, we can assign an address: https://github.com/docker/machine/blob/ab3b7acb9792271dcd349da731150757a9346183/drivers/virtualbox/virtualbox.go#L525 Not sure, but I expect this is also what vagrant uses to assign a private address. Not sure how this will work when the MAC address needs to be matched with an IP address, but this can be looked into...

Else I will continue with the original idea to override the address using an interface alias, such as `eth0:1`.

**Comment by gbraad** [comment]
On VirtualBox, I am able to assign an IP address on `eth1`. If I added a new host-only adapter, I can assign the address as follows:

`cat /var/lib/minishift/networking`
```
DEVICE=eth1
IPADDR=192.168.235.100
NETMASK=24
GATEWAY=192.168.235.1
DNS1=8.8.8.8
DNS2=8.8.4.4
```

**Comment by gbraad** [comment]
Testing on VirtualBox with https://github.com/minishift/minishift-centos-iso/pull/179 and the following configuration files:

`cat /var/lib/minishift/networking-eth0`
```ini
DEVICE=eth0
USEDHCP=y
```

`cat /var/lib/minishift/networking-eth1`
```ini
DEVICE=eth1
IPADDR=192.168.235.100
NETMASK=24
GATEWAY=192.168.235.1
DNS1=8.8.8.8
DNS2=8.8.4.4
```

**Comment by gbraad** [comment]
Moving between IP addresses possible:

![set-ipaddress](https://user-images.githubusercontent.com/1894/33114186-aba4cacc-cf96-11e7-8ceb-88b981d22d87.png)

**Comment by gbraad** [comment]
```
$ minishift ssh -- "echo REVWSUNFPWV0aDAKVVNFREhDUD15Cg== | base64 --decode | sud
o tee /var/lib/minishift/networking > /dev/null"
$ minishift ssh -- cat /var/lib/minishift/networking
DEVICE=eth0
USEDHCP=y
```

**Comment by gbraad** [comment]
The KVM driver has an issue with newly assigned addresses. It seems to resort to using the old address. Probably this is cached somewhere, either in the ARP table or from the DHCP lease?

**Comment by gbraad** [comment]
Have to work around the KVM driver and how this one sets the IP address based on the DHCP lease...

**Comment by gbraad** [comment]
I will postpone working on this: current code lives on https://github.com/gbraad/minishift/tree/issue-1457

**Comment by gbraad** [comment]
At the moment I can not provide support for KVM, as the driver needs to lookup the address from the DHCP lease information. We can resolve this with the KVM2 driver, by using the options file instead. In code, I exit with an error for the moment

**Comment by LalatenduMohanty** [comment]
Resolved via #1849
