### ISSUE TITLE
Possible plan to promote --network-ipaddress to general availability

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1513]
The functionality implemented in #1316 can come out of experimental use after:

Prerequisite : https://github.com/minishift/minishift-centos-iso/pull/179

  * [x] #1492 automagically assign default gateway
  * [x] #1497 assign multiple nameservers 
  * [x] #1493 automagically assign nameservers
  * [x] #1496 feature detection during provisioning to determine if ISO supports requested feature
  * [x] #1473 only send hvkvp values when VM is in state "Running"
  * [x] #1457 assign fixed IP address for other hypervisors

And possibly
  * [x] ~~#1765 set IP address for VirtualBox over the forwarded SSH port~~

Additionally, an improvement due to this add the alias for `--network-ipaddress` => `--ipaddress` as in that case there is no direct need to use flags for setting the gateway and nameserver.

**Comment by gbraad** [comment]
A lot of this has been mixed into the issue with #1457. Need to weed out some of the stuff...

Did propose https://github.com/minishift/minishift-centos-iso/pull/179

**Comment by gbraad** [comment]
Modified the milestone?

**Comment by LalatenduMohanty** [comment]
Resolved via #1849
